import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url));
const r = spawnSync(process.execPath, ["scripts/evaluate.mjs"], { cwd: root, encoding: "utf8", timeout: 60000 });
assert.equal(r.status, 0, r.stderr);
const report = JSON.parse(r.stdout);
assert.equal(report.population.attacks, 12);
assert.equal(report.population.benign, 12);
assert.equal(report.detection.count, 12);
assert.equal(report.falsePositives.count, 0);
assert.equal(report.unknown.length, 0);
assert.equal(report.mutations.length, 6);
assert.ok(report.mutations.every(m => m.status === "killed" && m.killedBy.length > 0 && m.benignRegressions.length === 0));
assert.match(report.corpusSha256, /^[a-f0-9]{64}$/);
assert.deepEqual(report.population, { attacks: 12, benign: 12, total: 24 });
console.log("✓ real corpus detects attacks, permits twins and kills six source mutants");
const { classify, validateCorpus, summarize } = await import("./evaluate.mjs");
assert.equal(classify({ status: 1, stdout: "" }), "unknown");
assert.equal(classify({ status: 0, stdout: "garbage" }), "unknown");
assert.equal(classify({ status: 0, stdout: "{}" }), "unknown");
assert.equal(classify({ status: 0, stdout: "" }), "allow");
assert.equal(classify({ status: 0, stdout: '{"hookSpecificOutput":{"permissionDecision":"deny"}}' }), "deny");
const failed = summarize([{ id: "a", expected: "deny", actual: "unknown" }, { id: "b", expected: "allow", actual: "deny" }]);
assert.deepEqual(failed.detection, { count: 0, denominator: 1 });
assert.deepEqual(failed.falsePositives, { count: 1, denominator: 1 });
assert.deepEqual(failed.unknown, ["a"]);
console.log("✓ crashed and unreadable outcomes stay unknown and remain in denominators");
const corpus = JSON.parse(readFileSync(new URL("../eval/corpus.v1.json", import.meta.url)));
assert.throws(() => validateCorpus({ ...corpus, cases: [] }));
assert.throws(() => validateCorpus({ ...corpus, cases: [...corpus.cases, corpus.cases[0]] }));
assert.throws(() => validateCorpus({ ...corpus, cases: corpus.cases.filter(x => x.expected !== "allow") }));
console.log("✓ empty, duplicate and control-free corpora refuse");
