#!/usr/bin/env node
// Exercise the distributable, not a source-tree import. No registry access or lifecycle scripts.
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const scratch = mkdtempSync(join(tmpdir(), "guardrails-package-"));
const npm = process.platform === "win32" ? "npm.cmd" : "npm";
function command(binary, args, cwd) {
  const windowsNpm = process.platform === "win32" && binary === npm;
  const result = spawnSync(binary, windowsNpm ? args.map(arg => `"${arg.replaceAll('"', '""')}"`) : args, {
    cwd, encoding: "utf8", timeout: 120000,
    // npm.cmd requires a Windows command shell. Paths are generated by this script,
    // never interpolated from user-controlled arguments.
    shell: windowsNpm,
    env: { ...process.env, npm_config_cache: join(scratch, "npm-cache"), HOOK_CTX: "test", HOOK_STATE_DIR: join(scratch, "state"), HOOK_FIRE_LOG: join(scratch, "fires") },
  });
  if (result.error || result.status !== 0)
    throw new Error(`${binary} ${args.join(" ")} failed: ${result.error?.message ?? result.stderr ?? result.signal}`);
  return result.stdout;
}
try {
  const packed = JSON.parse(command(npm, ["pack", "--json", "--ignore-scripts", "--pack-destination", scratch], root));
  const consumer = join(scratch, "consumer");
  mkdirSync(consumer);
  command(npm, ["install", "--prefix", consumer, "--offline", "--ignore-scripts", "--no-audit", "--no-fund", "--no-package-lock", join(scratch, packed[0].filename)], consumer);
  const cli = join(consumer, "node_modules", "agent-guardrails", "bin", "agent-guardrails.mjs");
  command(process.execPath, [cli, "init"], consumer);
  command(process.execPath, [cli, "doctor", "--strict"], consumer);
  command(process.execPath, [cli, "uninstall"], consumer);
  console.log(JSON.stringify({ schemaVersion: 1, verdict: "pass", package: packed[0].filename,
    integrity: packed[0].integrity, fileCount: packed[0].files.length,
    checks: ["pack", "offline-install", "init", "doctor-strict", "uninstall"] }, null, 2));
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
